### ISSUE TITLE
syncLinks does not work with await getDeviceInstance

### ISSUE THREAD

**Issue by PaulWieland** [apearson/insteon-plm#37]
```JavaScript 
let device = await getDeviceInstance(address, { debug: false, syncInfo: true, syncLinks: true });

console.log(device.links); // [] -> IT's Empty!!
```

The device.links are empty even when asking the constructor to `syncLinks`. `syncLinks` is being called, but something is not awaiting correctly. 

At first I thought it was because we are returning a new device without `await`:

```JavaScript
default: return new DimmableLightingDevice(deviceID, this, options);
```

But this did not fix the problem either:

```JavaScript
default: return await new DimmableLightingDevice(deviceID, this, options);
```

**Comment by apearson** [comment]
This is because of the async nature of the device class. 

To not hold up the entire event loop the constructor launches the syncLinks method but does not wait for it to complete.  The device class emits a 'ready' event once all info and links have been synced. 

```ts
const device = await modem.getDeviceInstance(address, { debug: false, syncLinks: true, syncInfo: true });
device.once('ready', () => deviceReady(modem, device)); 
```

Do you think this should work another way?

**Comment by PaulWieland** [comment]
No I think it’s fine the way it is, I just had forgotten about the onready event.
